site_name: Python for the Humanities
site_description: A community-curated catalogue of Python modules that are notably useful for the Humanities.

pages:
  - Catalogue: 'index.md'
  - Contributing: 'contributing.md'

repo_name: telota/python-for-the-humanities
repo_url: https://github.com/telota/python-for-the-humanities

theme: material
theme_dir: layout
extra_css:
  - extra.css
markdown_extensions:
  - extra
  - smarty
extra:
  palette:
    primary: blue grey
    accent: indigo

strict: True
